const express = require('express');
const app = express();
const elementsRouter = require(`${__dirname}/routes/elementsRouter`);
const labsRouter = require(`${__dirname}/routes/labsRouter`);
const laboratoristsRouter = require(`${__dirname}/routes/laboratoristsRouter`);
const fichaRouter = require(`${__dirname}/routes/fichaRouter`);
const labCargoRouter = require(`${__dirname}/routes/LabCargoRouter`);
app.use(express.json());
app.use('/api/v1/elementos', elementsRouter);
app.use('/api/v1/laboratorios', labsRouter);
app.use('/api/v1/laboratoristas', laboratoristsRouter);
app.use('/api/v1/ficha', fichaRouter);
app.use('/api/v1/laboraoristasACargo', labCargoRouter);
module.exports = app;
